import { getOriginalQuestionPresentation } from "./questionSources"
import { getFullTermDefinition } from "./questionDefinitions"

export interface QuizOption {
  letter: string
  text: string
  definition: string
}

export interface QuizQuestion {
  id: number
  prompt: string
  concept: string
  options: QuizOption[]
  correct: string[]
  chooseCount: number
  explanation: string
}

interface RawQuestion {
  id: number
  prompt: string
  concept: string
  options: string[]
  correct: string[]
  chooseCount?: number
  explanation: string
}

const glossary: Record<string, string> = {
  "Tabletop exercise": "A discussion-based rehearsal of a hypothetical incident response scenario.",
  Reporting: "Documenting forensic methods, evidence, findings, and conclusions.",
  Preservation: "Protecting collected evidence from alteration, often using hashes and chain-of-custody records.",
  Acquisition: "Collecting or imaging digital evidence from a device or storage medium.",
  Lighting: "A physical security measure that improves visibility and can discourage unwanted activity.",
  Bollard: "A sturdy post used to block or limit vehicle access to a protected area.",
  "Security guard": "A person who can deter, observe, challenge, and physically prevent unauthorized access.",
  Fencing: "A physical perimeter barrier that discourages entry and restricts access to a site.",
  "Video surveillance": "Cameras that record or monitor activity; primarily detective and deterrent.",
  "Passive reconnaissance": "Gathering target information from public sources without interacting with target systems.",
  "Known environment": "A penetration test in which the tester is given substantial information about the target.",
  "Active reconnaissance": "Probing a target directly, such as scanning its network or services.",
  "Physical penetration test": "An authorized attempt to bypass physical security and enter a facility.",
  Virus: "Malware that attaches to a host file and typically needs a user to execute it to spread.",
  Keylogger: "Software or hardware that records keystrokes, potentially capturing credentials.",
  Worm: "Self-replicating malware that can spread between systems without a host file.",
  Rootkit: "Malware designed to hide its presence and maintain privileged access.",
  "DNS attack": "An attack that abuses domain name resolution, such as redirecting or disrupting it.",
  "Buffer overflow": "A flaw where excess input overwrites adjacent memory and may cause a crash or code execution.",
  "Privilege escalation": "Gaining permissions beyond those initially granted, such as administrator access.",
  "Directory traversal": "Using ../ path sequences to try to access files outside an application's allowed directory.",
  Tokenization: "Replacing sensitive data with a substitute token that maps to the original in a protected system.",
  Hashing: "Applying a one-way function to produce a fixed-length digest.",
  Masking: "Hiding sensitive data with substitute characters or values.",
  Salting: "Adding a unique random value to a password before hashing it.",
  "Vulnerable software": "Software with a weakness that could be exploited, especially if unpatched.",
  Typosquatting: "Using a lookalike domain that exploits typing mistakes or visual confusion.",
  "Supply chain": "Vendors, components, and processes involved in delivering a product or service.",
  "Supply chain compromise": "Tampering with a vendor, component, or delivery process before a product reaches a customer.",
  Pretexting: "Using a fabricated story or identity to manipulate someone into disclosing information.",
  "Dark web": "Services reachable through specialized networks and not indexed like ordinary public websites.",
  "False positive": "An alert that incorrectly reports a threat or vulnerability that is not present.",
  CVE: "Common Vulnerabilities and Exposures: identifiers and descriptions for known vulnerabilities.",
  CVSS: "Common Vulnerability Scoring System: a framework for rating vulnerability severity.",
  "Iris scan": "A biometric factor based on distinctive patterns in the colored ring of the eye.",
  "Hardware authentication token": "A physical device that proves possession, often by storing or generating secrets.",
  Password: "A secret memorized value; an example of something you know.",
  "Mobile phone with one-time SMS code": "A phone receives a temporary code; the phone is a possession factor.",
  "Mobile phone with one-time passcode": "A phone receives or generates a temporary code; it represents possession.",
  Obfuscation: "Transforming code to make its logic harder to understand or reverse engineer.",
  Escrow: "Placing keys or other assets with a trusted third party for controlled recovery or release.",
  Impersonation: "Pretending to be another person or trusted entity to deceive a target.",
  Phishing: "Deceptive messages, commonly email, used to steal information or prompt unsafe actions.",
  Vishing: "Voice phishing carried out through phone calls or other voice communications.",
  Smishing: "SMS phishing that uses deceptive text messages and malicious links.",
  Containment: "Limiting an incident's spread and impact, for example by isolating systems.",
  "Lessons learned": "Reviewing response effectiveness and root causes to improve future defenses.",
  Recovery: "Restoring systems and services to normal operation after a threat is addressed.",
  Eradication: "Removing malware, attacker access, and other causes of compromise.",
  RPO: "Recovery Point Objective: the maximum acceptable amount of data loss measured in time.",
  MTBF: "Mean Time Between Failures: average operating time between system failures.",
  RTO: "Recovery Time Objective: the target maximum time to restore service after disruption.",
  MTTR: "Mean Time to Repair or Restore: average time needed to return a failed system to service.",
  "Load balancing": "Distributing incoming work across multiple servers to improve capacity and availability.",
  "Platform diversity": "Using different platforms to reduce shared exposure to one vendor-specific weakness.",
  "Uninterruptible power supply": "Battery-backed power that provides short-term runtime and graceful shutdown.",
  Generator: "A backup power source for longer outages that usually takes time to start.",
  RADIUS: "A protocol for centralized network access authentication and accounting.",
  Sandboxing: "Running software in an isolated environment to limit access to systems and data.",
  "Input validation": "Checking that user-provided data matches expected formats and rules.",
  "Code signing": "A digital signature that helps verify publisher identity and detect changes after signing.",
  "Data retention": "Keeping records for a defined period to satisfy business or legal requirements.",
  Certification: "Formal evidence or attestation that a process or standard has been completed.",
  Sanitization: "Irreversibly removing data from media so it cannot be recovered using appropriate methods.",
  Destruction: "Physically damaging media so it can no longer store or reveal data.",
  Corrective: "A control that repairs damage or restores operations after an incident.",
  Compensating: "An alternate safeguard used when a preferred control is unavailable or infeasible.",
  Detective: "A control that discovers or signals events, such as sensors or detection systems.",
  Preventative: "A control intended to stop or reduce the chance of an event before it occurs.",
  Mandatory: "Access based on centrally assigned classifications and clearances.",
  "Role-based": "Access granted according to a user's job role.",
  Discretionary: "Access control where an owner decides who may access a resource.",
  "Rule-based": "Access decisions driven by explicit system rules, such as firewall policies.",
  WAF: "Web Application Firewall: filters web traffic to help protect applications from attacks.",
  IDS: "Intrusion Detection System: identifies suspicious activity and raises alerts.",
  UTM: "Unified Threat Management: one appliance combining several network security functions.",
  WPA3: "A Wi-Fi security protocol that improves wireless authentication and encryption.",
  "Non-repudiation": "Evidence that helps prevent a party from credibly denying an action.",
  Availability: "Ensuring systems and information are accessible when authorized users need them.",
  Integrity: "Maintaining data accuracy and completeness and protecting it from unauthorized changes.",
  Confidentiality: "Preventing unauthorized people from viewing or disclosing protected information.",
  UPS: "Uninterruptible Power Supply: short-term battery power for continued operation or safe shutdown.",
  TLS: "Transport Layer Security: a protocol that encrypts and authenticates network communications.",
  "Jump server": "A hardened intermediary host used as a controlled entry point to internal systems.",
  "Facial recognition": "A biometric method that identifies or verifies a person using facial characteristics.",
  "Fingerprint identification": "A biometric method that identifies or verifies a person using fingerprint patterns.",
  PIN: "A personal identification number; an example of something you know.",
  "Financial gain": "A motivation to steal, extort, or disrupt for monetary benefit.",
  "Philosophical/political beliefs": "An ideological motivation commonly associated with hacktivist activity.",
  Espionage: "Covertly collecting sensitive information for strategic advantage.",
  Blackmail: "Threatening to reveal damaging information unless a demand is met.",
  Federation: "Trust between identity systems that lets users authenticate with an external identity provider.",
  "Least privilege": "Giving users and processes only the permissions needed for their tasks.",
  "Single sign-on": "Using one authentication event to access multiple related services.",
  OAuth: "An authorization framework for granting an application limited access to a resource.",
  "Impossible travel": "Sign-ins from distant locations too close together to be physically plausible.",
  "Concurrent session usage": "Multiple active sessions using the same account at the same time.",
  "Password spraying": "Trying a few common passwords against many accounts to avoid repeated lockouts.",
  "Bug bounty program": "A program that rewards authorized researchers for reporting eligible vulnerabilities.",
  "Penetration test": "An authorized assessment that tests defenses and reports exploitable weaknesses.",
  "Open source intelligence (OSINT)": "Information gathered from publicly available sources.",
  "Threat hunting": "Proactively searching systems and telemetry for threats automated alerts may have missed.",
  Acceptance: "Acknowledging a risk and choosing not to add further treatment at that time.",
  Mitigation: "Reducing a risk's likelihood or impact without necessarily eliminating it.",
  Transference: "Shifting some financial or operational consequences of risk to another party.",
  Avoidance: "Eliminating an activity or exposure so its associated risk no longer applies.",
  Reuse: "Using the same password on multiple accounts, increasing the impact of a compromise.",
  Length: "The number of characters in a password or passphrase.",
  Complexity: "The character variety and unpredictability of a password.",
  Expiration: "A policy requiring a password change after a defined period or event.",
  "Insider threat": "Risk from a person with authorized access who misuses it intentionally or accidentally.",
  "Shadow IT": "Technology used for work without organizational approval or oversight.",
  "Organized crime": "A coordinated criminal group often motivated by financial profit.",
  "Data masking": "Replacing sensitive values with obscured or synthetic values.",
  Steganography: "Concealing information inside another file, such as an image or audio recording.",
  "Unskilled attacker": "An inexperienced attacker who relies heavily on existing scripts or tools.",
  Hacktivist: "An attacker motivated primarily by political or ideological goals.",
  "Nation-state": "A government-sponsored or directed threat actor pursuing strategic goals.",
  Deterrent: "A control intended to discourage an attacker from attempting an action.",
  Biometrics: "Authentication based on physical or behavioral traits.",
  "Retina scan": "A biometric method that analyzes blood-vessel patterns at the back of the eye.",
  "False negative": "A missed detection where a real threat is incorrectly reported as absent.",
  "Alert tuning": "Adjusting detection rules to reduce noise while preserving useful alerts.",
  Sideloading: "Installing an application from outside the platform's official distribution channel.",
  Jailbreaking: "Removing device restrictions to gain additional system access.",
  Misconfiguration: "An unsafe or incorrect system setting that creates security exposure.",
  "Hash collision": "Two different inputs producing the same hash digest.",
  "Credential replay": "Reusing captured authentication material to impersonate a user.",
  "Watering hole": "Compromising a website likely to be visited by a target group.",
  "Business email compromise": "Fraud using a compromised or spoofed business email account.",
}

Object.assign(glossary, {
  "Data retention": "Keeping records for a defined period to meet business, legal, or regulatory requirements.",
  Certification: "Formal evidence that a process or standard has been completed.",
  Sanitization: "Irreversibly removing data from media so it cannot be recovered by appropriate methods.",
  Destruction: "Physically damaging media so it cannot be reused or have its data recovered.",
  Corrective: "A control that repairs damage or restores operations after an incident.",
  Compensating: "An alternate safeguard used when a preferred control is unavailable or infeasible.",
  Detective: "A control that discovers or signals events, such as sensors or detection systems.",
  Preventative: "A control intended to stop or reduce the chance of an event before it occurs.",
  Mandatory: "Access based on centrally assigned classifications and clearances.",
  "Role-based": "Access granted according to a user's job role.",
  Discretionary: "Access control where an owner decides who may access a resource.",
  "Rule-based": "Access decisions driven by explicit system rules, such as firewall policies.",
  WAF: "Web Application Firewall: filters web traffic to help protect applications from attacks.",
  IDS: "Intrusion Detection System: identifies suspicious activity and raises alerts.",
  UTM: "Unified Threat Management: one appliance combining several network security functions.",
  WPA3: "A Wi-Fi security protocol that improves wireless authentication and encryption.",
  "Non-repudiation": "Evidence that helps prevent a party from credibly denying an action.",
  Availability: "Ensuring systems and information are accessible when authorized users need them.",
  Integrity: "Maintaining data accuracy and protecting it from unauthorized changes.",
  Confidentiality: "Preventing unauthorized people from viewing or disclosing protected information.",
  UPS: "Uninterruptible Power Supply: short-term battery power for continued operation or safe shutdown.",
  TLS: "Transport Layer Security: a protocol that encrypts and authenticates network communications.",
  "Jump server": "A hardened intermediary host used as a controlled entry point to internal systems.",
  "Facial recognition": "A biometric method that identifies or verifies a person using facial characteristics.",
  "Fingerprint identification": "A biometric method that identifies or verifies a person using fingerprint patterns.",
  "Financial gain": "A motivation to steal, extort, or disrupt for monetary benefit.",
  "Philosophical/political beliefs": "An ideological motivation commonly associated with hacktivist activity.",
  Espionage: "Covertly collecting sensitive information for strategic advantage.",
  Blackmail: "Threatening to reveal damaging information unless a demand is met.",
  Federation: "Trust between identity systems that lets users authenticate with an external identity provider.",
  "Least privilege": "Giving users and processes only the permissions needed for their tasks.",
  "Single sign-on": "Using one authentication event to access multiple related services.",
  OAuth: "An authorization framework for granting an application limited access to a resource.",
  "Impossible travel": "Sign-ins from distant locations too close together to be physically plausible.",
  "Brute force": "Repeatedly trying many passwords against one account or encrypted value.",
  "Concurrent session usage": "Multiple active sessions using the same account at the same time.",
  "Password spraying": "Trying a few common passwords against many accounts to avoid repeated lockouts.",
  "Bug bounty program": "A program that rewards authorized researchers for reporting eligible vulnerabilities.",
  "Penetration test": "An authorized assessment that tests defenses and reports exploitable weaknesses.",
  "Open source intelligence (OSINT)": "Information gathered from publicly available sources.",
  "Threat hunting": "Proactively searching for threats that automated alerts may have missed.",
  Acceptance: "Acknowledging a risk and choosing not to add further treatment at that time.",
  Mitigation: "Reducing a risk's likelihood or impact without necessarily eliminating it.",
  Transference: "Shifting some financial or operational consequences of risk to another party.",
  Avoidance: "Eliminating an activity or exposure so its associated risk no longer applies.",
  Reuse: "Using the same password on multiple accounts, increasing the impact of a compromise.",
  Length: "The number of characters in a password or passphrase.",
  Complexity: "The character variety and unpredictability of a password.",
  Expiration: "A policy requiring a password change after a defined period or event.",
})

Object.assign(glossary, {
  "Insider threat": "Risk from a person with authorized access who misuses it intentionally or accidentally.",
  "Shadow IT": "Technology used for work without organizational approval or oversight.",
  "Organized crime": "A coordinated criminal group often motivated by financial profit.",
  "Data masking": "Replacing sensitive values with obscured or synthetic values.",
  Steganography: "Concealing information inside another file, such as an image or audio recording.",
  "Unskilled attacker": "An inexperienced attacker who relies heavily on existing scripts or tools.",
  Hacktivist: "An attacker motivated primarily by political or ideological goals.",
  "Nation-state": "A government-sponsored or directed threat actor pursuing strategic goals.",
  Deterrent: "A control intended to discourage an attacker from attempting an action.",
  Biometrics: "Authentication based on physical or behavioral traits.",
  "Retina scan": "A biometric method that analyzes blood-vessel patterns at the back of the eye.",
  "False negative": "A missed detection where a real threat is incorrectly reported as absent.",
  "Alert tuning": "Adjusting detection rules to reduce noise while preserving useful alerts.",
  Sideloading: "Installing an application from outside the platform's official distribution channel.",
  Jailbreaking: "Removing device restrictions to gain additional system access.",
  Misconfiguration: "An unsafe or incorrect system setting that creates security exposure.",
  "Hash collision": "Two different inputs producing the same hash digest.",
  "Credential replay": "Reusing captured authentication material to impersonate a user.",
  "Watering hole": "Compromising a website likely to be visited by a target group.",
  "Business email compromise": "Fraud using a compromised or spoofed business email account.",
  Spyware: "Software that secretly monitors activity and may send collected information to an attacker.",
  "Data subject": "The person whose personal information is being collected, held, or processed.",
  "Data sovereignty": "The laws and regulations that apply to data based on where it is stored or processed.",
})

const rawQuestions: RawQuestion[] = [
  { id: 31, concept: "Governance", prompt: "Employees in a shipping department use an unapproved third-party application to improve work efficiency. What best describes this situation?", options: ["Pretexting", "Insider threat", "Shadow IT", "Organized crime"], correct: ["Shadow IT"], explanation: "Shadow IT is technology adopted for work without organizational approval or oversight. An insider threat involves misuse of authorized access; pretexting is social engineering, and organized crime describes a threat actor group." },
  { id: 32, concept: "Software security", prompt: "A developer wants to make a public application difficult to reverse engineer and reveal its source code. What technique best addresses this concern?", options: ["Masking", "Obfuscation", "Tokenization", "Steganography"], correct: ["Obfuscation"], explanation: "Obfuscation transforms code to make its logic harder to understand or reverse engineer. Masking obscures data, tokenization substitutes a token for sensitive data, and steganography hides information inside another file." },
  { id: 33, concept: "Threat actors", prompt: "A company's public-facing websites are defaced with political messages and beliefs. Which attacker best fits this motivation?", options: ["Unskilled attacker", "Insider threat", "Hacktivist", "Nation-state"], correct: ["Hacktivist"], explanation: "Hacktivists are motivated primarily by political or ideological goals and may deface websites to promote a message. Nation-state actors more commonly pursue strategic goals such as espionage." },
  { id: 34, concept: "Security controls", prompt: "After a fire damages critical servers, an organization repairs affected systems and restores services to normal operation. Which control type is being used?", options: ["Corrective", "Preventative", "Detective", "Deterrent"], correct: ["Corrective"], explanation: "Corrective controls repair damage and restore operations after an incident. Preventative controls aim to stop incidents, detective controls identify them, and deterrent controls discourage attempts." },
  { id: 35, concept: "Authentication factors", prompt: "A company already uses employee fingerprints, mobile phones with one-time SMS codes, and IP geolocation. Which option adds an additional authentication factor?", options: ["PIN", "Hardware authentication token", "Biometrics", "Retina scan"], correct: ["PIN"], explanation: "A PIN is something you know. Fingerprints and retina scans are biometrics; phones and hardware tokens are possession factors. The PIN adds the missing knowledge factor." },
  { id: 36, concept: "Incident response", prompt: "Ransomware-infected systems are isolated from the network by disconnecting their Ethernet cables. Which incident response phase should happen next?", options: ["Lessons learned", "Eradication", "Recovery", "Containment"], correct: ["Eradication"], explanation: "After containment isolates infected systems, eradication removes malware and attacker access. Recovery follows eradication to restore services; lessons learned reviews the response afterward." },
  { id: 37, concept: "Security monitoring", prompt: "Company-approved software causes monitoring systems to generate a large volume of unnecessary security notifications. What should the analyst do to reduce the noise?", options: ["False negative", "Alert tuning", "False positive", "CVE"], correct: ["Alert tuning"], explanation: "Alert tuning adjusts detection rules to reduce unnecessary notifications while preserving useful detections. A false positive is one type of incorrect alert; a false negative is a missed threat." },
  { id: 38, concept: "Mobile security", prompt: "A policy prohibits employees from modifying personal-device firmware to remove restrictions and install unauthorized applications. What behavior is being addressed?", options: ["Sideloading", "Jailbreaking", "Misconfiguration", "Supply chain"], correct: ["Jailbreaking"], explanation: "Jailbreaking removes manufacturer restrictions and can enable elevated access or unauthorized app installation. Sideloading means installing apps outside an official store; it can occur without jailbreaking on some platforms." },
  { id: 39, concept: "Resilience metrics", prompt: "A technician estimates that restoring a network router to full functionality will take an average of one hour. Which metric is described?", options: ["RTO", "MTTR", "RPO", "MTBF"], correct: ["MTTR"], explanation: "MTTR is the average time to repair or restore a failed device. MTBF is average operating time between failures, RTO is the target restoration window, and RPO is the tolerable data-loss window." },
  { id: 40, concept: "Social engineering", prompt: "A user receives text messages with suspicious links to third-party websites that request sensitive passwords. What type of attack is this?", options: ["Spyware", "Smishing", "Typosquatting", "Phishing"], correct: ["Smishing"], explanation: "Smishing is phishing delivered by SMS or text. Email-based deception is commonly called phishing; spyware monitors activity, and typosquatting uses lookalike domain names." },
  { id: 41, concept: "Risk management", prompt: "A security company buys cybersecurity insurance in preparation for possible ransomware incidents. Which risk response is this?", options: ["Transference", "Mitigation", "Avoidance", "Acceptance"], correct: ["Transference"], explanation: "Insurance transfers some financial consequences of risk to a third party. Mitigation reduces likelihood or impact, avoidance removes the exposure, and acceptance acknowledges risk without further treatment." },
  { id: 42, concept: "Risk management", prompt: "A cybersecurity firm updates systems, isolates critical applications, and installs web application firewalls. Which risk response best describes these actions?", options: ["Mitigation", "Transference", "Acceptance", "Avoidance"], correct: ["Mitigation"], explanation: "Patching, isolation, and WAFs reduce the likelihood or impact of attacks, so they are mitigation. They lower risk but do not guarantee its elimination." },
  { id: 43, concept: "Data governance", prompt: "An organization must store all emails for one year before deleting them. What requirement is being described?", options: ["Data retention", "Data masking", "Data subject", "Data sovereignty"], correct: ["Data retention"], explanation: "Data retention defines how long information must be kept. Masking obscures values, a data subject is the person the data is about, and sovereignty concerns the laws governing data based on location." },
  { id: 44, concept: "Web attacks", prompt: "A nation-state attacker uses public sources to identify websites employees often visit, then exploits a zero-day vulnerability on one of them. What attack is this?", options: ["Typosquatting", "Vishing", "Watering hole", "Business email compromise"], correct: ["Watering hole"], explanation: "A watering-hole attack compromises a website likely to be visited by a target group, then uses it to reach those targets. Typosquatting relies on lookalike domains; vishing uses voice calls." },
  { id: 45, concept: "Credential attacks", prompt: "A SOC analyst sees repeated unsuccessful attempts against one account, each using a different password. What is most likely occurring?", options: ["Password spraying", "Brute force", "Hash collision", "Credential replay"], correct: ["Brute force"], explanation: "Brute force tries many different passwords against a single account. Password spraying tries a small set of common passwords across many accounts. A hash collision is two inputs with the same digest; credential replay reuses captured authentication material." },
  { id: 16, concept: "Media handling", prompt: "An employee is preparing a storage drive for reuse and wants to ensure its previous sensitive data cannot be recovered. What should they request?", options: ["Data retention", "Certification", "Sanitization", "Destruction"], correct: ["Sanitization"], explanation: "Sanitization removes data so it cannot be recovered and is suitable when a drive will be reused. Destruction physically renders media unusable; certification documents a process, and retention concerns how long data must be kept." },
  { id: 17, concept: "Security controls", prompt: "A security company installs CCTV and sensors to monitor potential intruders but has no budget for additional security features. Which control type best describes the controls in use?", options: ["Corrective", "Compensating", "Detective", "Preventative"], correct: ["Detective"], explanation: "Cameras and sensors primarily detect and record activity or raise alerts. Preventative controls stop an event, corrective controls restore operations afterward, and compensating controls provide an alternate safeguard." },
  { id: 18, concept: "Access control", prompt: "A file owner decides which users can access the resources they own. Which access control method is most likely being used?", options: ["Mandatory", "Role-based", "Discretionary", "Rule-based"], correct: ["Discretionary"], explanation: "Discretionary access control lets the resource owner decide who may access it. Mandatory access control uses central labels and clearances; role-based access follows job roles, and rule-based access follows configured system rules." },
  { id: 19, concept: "Application security", prompt: "A developer uses input validation against cross-site scripting and SQL injection and wants additional protection for customer data. Which control is most appropriate?", options: ["WAF", "IDS", "UTM", "WPA3"], correct: ["WAF"], explanation: "A Web Application Firewall filters web traffic and can help block attacks such as SQL injection and cross-site scripting. An IDS detects and alerts, UTM combines network controls, and WPA3 protects wireless networks." },
  { id: 20, concept: "Security objectives", prompt: "An administrator deploys VPN software to provide encrypted tunnels and protect data from on-path attackers. Which security objective is most directly associated with this?", options: ["Non-repudiation", "Availability", "Integrity", "Confidentiality"], correct: ["Confidentiality"], explanation: "Encryption protects confidentiality by making intercepted data unreadable without the appropriate key. Integrity protects against unauthorized changes, availability ensures access when needed, and non-repudiation provides evidence that an action occurred." },
  { id: 21, concept: "Availability", prompt: "A company experiences unexpected shutdowns and data loss. It needs a short-term solution that allows devices to shut down gracefully. What should it implement?", options: ["UPS", "TLS", "Generator", "Jump server"], correct: ["UPS"], explanation: "A UPS provides short-term battery power so equipment can continue briefly or shut down cleanly. A generator supports longer outages but may take time to start. TLS protects network traffic; a jump server controls access to internal systems." },
  { id: 22, concept: "Resilience metrics", prompt: "A help desk technician calculates the average amount of time a Linux system will run before it fails. Which metric is this?", options: ["RTO", "RPO", "MTBF", "MTTR"], correct: ["MTBF"], explanation: "MTBF estimates average operating time between failures. MTTR measures repair time, RTO is the target time to restore service, and RPO is the acceptable data-loss window." },
  { id: 23, concept: "Authentication factors", prompt: "An organization already uses iris scans, smart cards, and hardware authentication tokens. Which option adds a new authentication factor?", options: ["Facial recognition", "Fingerprint identification", "Mobile phone with one-time passcode", "PIN"], correct: ["PIN"], explanation: "A PIN is something you know. Iris scans, facial recognition, and fingerprints are something you are; smart cards, hardware tokens, and phones are something you have. The PIN adds a distinct factor category." },
  { id: 24, concept: "Threat actors", prompt: "An organized crime group installs ransomware that encrypts company files and changes their extensions. What is the most likely motivation?", options: ["Financial gain", "Philosophical/political beliefs", "Espionage", "Blackmail"], correct: ["Financial gain"], explanation: "Organized crime commonly deploys ransomware for financial gain, demanding payment for a decryption key or threatening data exposure. Political beliefs are more associated with hacktivism; espionage focuses on covert collection." },
  { id: 25, concept: "Identity and access management", prompt: "An employee opens a company portal and can authenticate using existing credentials from a trusted third-party identity provider. What is most likely being used?", options: ["Federation", "Least privilege", "Single sign-on", "OAuth"], correct: ["Federation"], explanation: "Federation establishes trust between separate identity systems so users can authenticate with an external identity provider. Single sign-on provides access to multiple services after one sign-in; OAuth is primarily an authorization framework." },
  { id: 26, concept: "Incident response", prompt: "After a company-wide malware incident, the incident response team performs root cause analysis to prevent recurrence. Which phase is this?", options: ["Lessons learned", "Eradication", "Containment", "Recovery"], correct: ["Lessons learned"], explanation: "Root cause analysis and review of response improvements occur during lessons learned. Containment limits spread, eradication removes the threat, and recovery restores services." },
  { id: 27, concept: "Identity analytics", prompt: "One employee account has logins from distant countries within a time span that makes the travel physically impossible. What did the administrator most likely detect?", options: ["Brute force", "Impossible travel", "Password spraying", "Concurrent session usage"], correct: ["Impossible travel"], explanation: "Impossible travel flags sign-ins from geographically distant locations too close together to be plausible. Concurrent sessions only indicate simultaneous use. Brute force and spraying are password-guessing patterns." },
  { id: 28, concept: "Security testing", prompt: "An ethical hacking program compensates participants based on the vulnerabilities they find and report. What is this program?", options: ["Bug bounty program", "Penetration test", "Open source intelligence (OSINT)", "Threat hunting"], correct: ["Bug bounty program"], explanation: "A bug bounty rewards authorized researchers for eligible vulnerability reports. A penetration test is a broader scoped assessment, OSINT gathers public information, and threat hunting searches for active threats." },
  { id: 29, concept: "Risk management", prompt: "An organization implements controls to reduce the likelihood or potential impact of identified risks. Which risk response is this?", options: ["Acceptance", "Mitigation", "Transference", "Avoidance"], correct: ["Mitigation"], explanation: "Risk mitigation reduces likelihood or impact but does not necessarily eliminate risk. Avoidance removes exposure, transference shifts some consequences to another party, and acceptance chooses not to add further treatment." },
  { id: 30, concept: "Password security", prompt: "A website requires passwords to include numbers, symbols, and letters to resist guessing. Which password property is being emphasized?", options: ["Reuse", "Length", "Complexity", "Expiration"], correct: ["Complexity"], explanation: "Complexity concerns character variety and unpredictability. Length is the number of characters; reuse means using a password on multiple accounts, and expiration is a change interval." },
  { id: 1, concept: "Digital forensics", prompt: "A digital forensics team investigating a crime scene implements integrity controls to ensure collected data is not tampered with or modified. Which phase is this?", options: ["Tabletop exercise", "Reporting", "Preservation", "Acquisition"], correct: ["Preservation"], explanation: "Preservation protects evidence after collection. Investigators commonly calculate hashes and maintain chain-of-custody records. Acquisition is the collection step; reporting documents methods and findings. A tabletop exercise is an incident-response rehearsal." },
  { id: 2, concept: "Physical security", prompt: "A software company has noticed suspicious individuals surrounding its facility at night. It wants preventive and deterrent controls to stop this from recurring. Which TWO should it implement?", options: ["Lighting", "Bollard", "Security guard", "Fencing", "Video surveillance"], correct: ["Security guard", "Fencing"], chooseCount: 2, explanation: "Security guards and fencing can both deter people and physically impede unauthorized access. Lighting and video surveillance can deter and detect activity, but do not create a physical barrier. Bollards are designed mainly to stop vehicles." },
  { id: 3, concept: "Reconnaissance", prompt: "A nation-state threat actor performs port and vulnerability scans against a company network. The IPS detects and blocks the scans in real time. What was the attacker most likely attempting?", options: ["Passive reconnaissance", "Known environment", "Active reconnaissance", "Physical penetration test"], correct: ["Active reconnaissance"], explanation: "Active reconnaissance directly interacts with target systems, for example through network scanning. Passive reconnaissance uses public sources without probing the target. A known environment describes a tester's level of prior knowledge." },
  { id: 4, concept: "Malware", prompt: "A scan finds port 445 open, default credentials on many systems, and unpatched devices. Which malware is most likely to spread across the network without user action?", options: ["Virus", "Keylogger", "Worm", "Rootkit"], correct: ["Worm"], explanation: "A worm can self-replicate and spread without a user launching an infected host file. WannaCry is a well-known ransomware worm that exploited SMB vulnerabilities associated with port 445. Viruses typically rely on a host file; keyloggers record keystrokes and rootkits hide privileged access." },
  { id: 5, concept: "Web attacks", prompt: "An attacker attempts to access files outside an e-commerce website's web root by using ../ sequences. Which attack is this?", options: ["DNS attack", "Buffer overflow", "Privilege escalation", "Directory traversal"], correct: ["Directory traversal"], explanation: "Directory traversal uses path sequences such as ../ to try to reach files outside an application's intended directory. Privilege escalation increases permissions, a buffer overflow corrupts adjacent memory, and DNS attacks target name resolution." },
  { id: 6, concept: "Data protection", prompt: "An attacker exploits a SQL database but sees stored data replaced by asterisks and false information. Which technique is most likely being used?", options: ["Tokenization", "Hashing", "Masking", "Salting"], correct: ["Masking"], explanation: "Data masking obscures real values with characters such as asterisks or substitute data. Hashing is a one-way transformation, salting adds random data before hashing, and tokenization substitutes a token that maps to protected data." },
  { id: 7, concept: "Supply chain security", prompt: "A cybersecurity firm discovers counterfeit network routers were substituted for legitimate equipment before reaching the company. What is this most likely describing?", options: ["Vulnerable software", "Typosquatting", "Supply chain compromise", "Pretexting"], correct: ["Supply chain compromise"], explanation: "A supply chain compromise tampers with a product or delivery process before it reaches the customer. Typosquatting uses lookalike domains; pretexting is a fabricated story used to manipulate a person." },
  { id: 8, concept: "Vulnerability management", prompt: "A vulnerability scan finds critical issues with severity scores of 8/10, and the administrator prioritizes remediation using those ratings. Which system is being used?", options: ["Dark web", "False positive", "CVE", "CVSS"], correct: ["CVSS"], explanation: "CVSS rates vulnerability severity to support prioritization. CVE identifiers name known vulnerabilities but do not provide the severity score themselves. A false positive is an incorrect alert." },
  { id: 9, concept: "Authentication factors", prompt: "An organization uses facial recognition, smart cards, and fingerprint identification. Which option would add a different authentication factor?", options: ["Iris scan", "Hardware authentication token", "Password", "Mobile phone with one-time SMS code"], correct: ["Password"], explanation: "A password is something you know. Facial recognition and iris scans are something you are; smart cards, hardware tokens, and phones are something you have. A password adds a distinct factor category." },
  { id: 10, concept: "Password security", prompt: "A database administrator adds random alphanumeric characters to each password before applying a one-way, fixed-length algorithm. What are they using?", options: ["Obfuscation", "Escrow", "Salting", "Hashing"], correct: ["Salting"], explanation: "Salting adds a unique random value to a password before it is hashed. Hashing is the one-way transformation itself. Escrow places keys with a trusted third party; obfuscation makes code harder to understand." },
  { id: 11, concept: "Social engineering", prompt: "An employee receives fraudulent text messages from an unknown number claiming to be the help desk. Each contains a link to a third-party website. What attack is most likely occurring?", options: ["Impersonation", "Phishing", "Vishing", "Smishing"], correct: ["Smishing"], explanation: "Smishing is phishing delivered through SMS or text messages. Vishing uses voice calls, while phishing commonly refers to deceptive email. Impersonation is pretending to be someone else and may be part of the attack." },
  { id: 12, concept: "Incident response", prompt: "After a malware infection, an incident response team uses offsite backups to restore systems to their prior state. Which phase are they performing?", options: ["Containment", "Lessons learned", "Recovery", "Eradication"], correct: ["Recovery"], explanation: "Recovery restores systems and services to normal operation, often from clean backups. Containment isolates affected systems, eradication removes malware and attacker access, and lessons learned reviews the incident afterward." },
  { id: 13, concept: "Resilience metrics", prompt: "A company estimates the average time required to restore a failed network router to full functionality. Which metric is this?", options: ["RPO", "MTBF", "RTO", "MTTR"], correct: ["MTTR"], explanation: "MTTR is Mean Time to Repair or Restore: the average time needed to return a failed device to service. MTBF measures operating time between failures. RTO is the target restoration time; RPO is the acceptable data-loss window." },
  { id: 14, concept: "Availability", prompt: "A hardware startup's public web servers suffer DDoS attacks that make them unavailable to paying customers. Which technology can improve availability by distributing traffic?", options: ["Load balancing", "Platform diversity", "Uninterruptible power supply", "Generator"], correct: ["Load balancing"], explanation: "Load balancing distributes incoming traffic across multiple servers and can help maintain availability when capacity is stressed. It is not a complete DDoS defense by itself. The other options address vendor diversity or power continuity." },
  { id: 15, concept: "Software security", prompt: "A developer wants customers to verify that an application came from the legitimate developer and has not been modified since release. What should they use?", options: ["RADIUS", "Sandboxing", "Input validation", "Code signing"], correct: ["Code signing"], explanation: "Code signing attaches a publisher's digital signature so users can verify origin and detect changes after signing. Sandboxing isolates execution, input validation checks supplied data, and RADIUS provides centralized network authentication." },
]

export const questionBank: QuizQuestion[] = rawQuestions.sort((left, right) => left.id - right.id).map((question) => {
  const source = getOriginalQuestionPresentation(question.id)
  const correctAnswers = question.id === 7 ? ["supply chain"] : question.correct
  return {
    ...question,
    prompt: source.prompt || question.prompt,
    correct: correctAnswers,
    chooseCount: question.chooseCount ?? 1,
    options: (source.options.length ? source.options : question.options).map((text, index) => {
      const definition = Object.entries(glossary).find(([term]) => term.toLowerCase() === text.toLowerCase())?.[1]
      return {
        letter: String.fromCharCode(65 + index),
        text,
        definition: getFullTermDefinition(question.id, text) ?? definition ?? `${text} is a security term. Review the explanation after submitting your answer.`,
      }
    }),
  }
})